// src/lib/configurator/debug/debug-menu.svelte
<!-- 
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
  import CommitSlider from "$lib/components/commit-slider.svelte"
  import FixedScrollArea from "$lib/components/fixed-scroll-area.svelte"
  import * as KeyTester from "$lib/components/key-tester"
  import { Button } from "$lib/components/ui/button"
  import { keyboardContext } from "$lib/keyboard"
  import { analogInfoQueryContext } from "../queries/analog-info-query.svelte"
  import { calibrationQueryContext } from "../queries/calibration.query.svelte"

  const {
    demo,
    metadata: { adcBits },
  } = keyboardContext.get()

  const analogInfoQuery = analogInfoQueryContext.get()
  const calibrationQuery = calibrationQueryContext.get()
  const { current: calibration } = $derived(calibrationQuery.calibration)
</script>

<div class="grid size-full grid-cols-[minmax(0,1fr)_24rem]">
  <FixedScrollArea class="flex flex-col gap-4 p-4">
    <CommitSlider
      bind:committed={
        () => calibration?.initialRestValue ?? 0,
        (v) =>
          calibration &&
          calibrationQuery.set({
            data: {
              ...calibration,
              initialRestValue: v,
            },
          })
      }
      description="The initial noise floor represents the estimated analog value when a key is at rest. It should be set slightly higher than the actual analog readings of all keys in their resting position to prevent deadzones. Recalibrate the keyboard to apply changes. This setting applies globally across all profiles."
      disabled={demo || !calibration}
      min={0}
      max={(1 << adcBits) - 1}
      step={10}
      title="Initial Noise Floor"
    />
    <CommitSlider
      bind:committed={
        () => calibration?.initialBottomOutThreshold ?? (1 << adcBits) - 1,
        (v) =>
          calibration &&
          calibrationQuery.set({
            data: {
              ...calibration,
              initialBottomOutThreshold: v,
            },
          })
      }
      description="The initial bottom out threshold represents the estimated change in analog value when a key is fully pressed. It should be set slightly lower than the actual change in analog readings when keys are fully pressed to prevent deadzones. Recalibrate the keyboard to apply changes. This setting applies globally across all profiles."
      disabled={demo || !calibration}
      min={0}
      max={(1 << adcBits) - 1}
      step={10}
      title="Initial Bottom Out Threshold"
    />
    <div>
      <Button
        disabled={demo}
        onclick={() => analogInfoQuery.recalibrate()}
        size="sm"
      >
        Recalibrate
      </Button>
    </div>
  </FixedScrollArea>
  <FixedScrollArea class="flex flex-col gap-4 p-4">
    <KeyTester.Root>
      <div class="flex flex-col gap-2">
        <div class="text-sm font-medium">Pressed Keys</div>
        <KeyTester.Press class="h-32 w-full" />
      </div>
      <div class="flex flex-col gap-2">
        <div class="text-sm font-medium">Released Keys</div>
        <KeyTester.Release class="h-32 w-full" />
      </div>
    </KeyTester.Root>
  </FixedScrollArea>
</div>

// components/configurator/debug/debug-menu.tsx
/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { FixedScrollArea } from "@/components/common/fixed-scroll-area"
import { useKeyboard } from "@/components/providers/keyboard-provider"
import { Button } from "@/components/ui/button"
import { useGetCalibration } from "@/queries/get-calibration"
import { useRecalibrate } from "@/queries/recalibrate"

import { CommitSlider, CommitSliderProvider } from "../common/commit-slider"
import {
  KeyTesterKeyPress,
  KeyTesterKeyRelease,
  KeyTesterProvider,
} from "../common/key-tester"

export function DebugMenu() {
  const {
    metadata: { adcBits },
    isDemo,
  } = useKeyboard()

  const { isSuccess, data: calibration } = useGetCalibration()
  const { mutate: recalibrate } = useRecalibrate()

  return (
    <div className="grid size-full grid-cols-[minmax(0,1fr)_24rem]">
      <FixedScrollArea>
        <div className="flex flex-col gap-4 p-4">
          <CommitSliderProvider
            description="The initial noise floor represents the estimated analog value when a key is at rest. It should be set slightly higher than the actual analog readings of all keys in their resting position to prevent deadzones. Recalibrate the keyboard to apply changes. This setting applies globally across all profiles."
            disabled={!isSuccess || isDemo}
            title="Initial Noise Floor"
          >
            <CommitSlider
              committedValue={calibration?.initialRestValue}
              min={0}
              max={(1 << adcBits) - 1}
              step={10}
            />
          </CommitSliderProvider>
          <CommitSliderProvider
            description="The initial bottom out threshold represents the estimated change in analog value when a key is fully pressed. It should be set slightly lower than the actual change in analog readings when keys are fully pressed to prevent deadzones. Recalibrate the keyboard to apply changes. This setting applies globally across all profiles."
            disabled={!isSuccess || isDemo}
            title="Initial Bottom Out Threshold"
          >
            <CommitSlider
              committedValue={calibration?.initialBottomOutThreshold}
              min={0}
              max={(1 << adcBits) - 1}
              step={10}
            />
          </CommitSliderProvider>
          <div>
            <Button disabled={isDemo} onClick={() => recalibrate()} size="sm">
              Recalibrate
            </Button>
          </div>
        </div>
      </FixedScrollArea>
      <FixedScrollArea>
        <KeyTesterProvider>
          <div className="flex flex-col gap-2 p-4">
            <div className="flex flex-col gap-2">
              <div className="text-sm font-medium">Pressed Keys</div>
              <KeyTesterKeyPress className="h-32" />
            </div>
            <div className="flex flex-col gap-2">
              <div className="text-sm font-medium">Released Keys</div>
              <KeyTesterKeyRelease className="h-32" />
            </div>
          </div>
        </KeyTesterProvider>
      </FixedScrollArea>
    </div>
  )
}
