// src/lib/components/keycode-button/keycode-button.svelte
<!-- 
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
  import { getKeycodeMetadata } from "$lib/keycodes"
  import type { WithoutChildren } from "$lib/utils"
  import type { ComponentProps } from "svelte"
  import { KeyButton } from "../key-button"
  import KeycodeButtonTooltip from "./keycode-button-tooltip.svelte"

  const {
    keycode,
    showTooltip,
    ...props
  }: WithoutChildren<ComponentProps<typeof KeyButton>> & {
    keycode: number
    showTooltip?: boolean
  } = $props()

  const { name, display } = $derived(getKeycodeMetadata(keycode))
</script>

<KeycodeButtonTooltip {keycode} {showTooltip}>
  <KeyButton {...props}>
    {#each display ?? [name] as Variant, i (i)}
      {#if typeof Variant === "string"}
        <span>{Variant}</span>
      {:else}
        <Variant />
      {/if}
    {/each}
  </KeyButton>
</KeycodeButtonTooltip>

// src/components/configurator/common/keycode-button.tsx
/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { Button } from "@/components/ui/button"
import { KEYCODE_TO_METADATA } from "@/constants/keycodes"
import { cn } from "@/lib/utils"
import { ComponentProps } from "react"

interface KeycodeButtonProps extends ComponentProps<typeof Button> {
  keycode: number
}

export function KeycodeButton({
  keycode,
  className,
  ...props
}: KeycodeButtonProps) {
  const keycodeMetadata = KEYCODE_TO_METADATA[keycode]

  return (
    <Button
      variant="outline"
      size="icon"
      className={cn("size-full flex-col gap-0", className)}
      {...props}
    >
      {keycodeMetadata.display ?? keycodeMetadata.id}
    </Button>
  )
}
