// src/lib/components/keycode-button/keycode-button.svelte
<!-- 
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
  import { getKeycodeMetadata } from "$lib/keycodes"
  import type { WithoutChildren } from "$lib/utils"
  import type { ComponentProps } from "svelte"
  import { KeyButton } from "../key-button"
  import KeycodeButtonTooltip from "./keycode-button-tooltip.svelte"

  const {
    keycode,
    showTooltip,
    ...props
  }: WithoutChildren<ComponentProps<typeof KeyButton>> & {
    keycode: number
    showTooltip?: boolean
  } = $props()

  const { name, display } = $derived(getKeycodeMetadata(keycode))
</script>

<KeycodeButtonTooltip {keycode} {showTooltip}>
  <KeyButton {...props}>
    {#each display ?? [name] as Variant, i (i)}
      {#if typeof Variant === "string"}
        <span>{Variant}</span>
      {:else}
        <Variant />
      {/if}
    {/each}
  </KeyButton>
</KeycodeButtonTooltip>

// components/configurator/common/keycode-button.tsx
/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { useMemo } from "react"

import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { useKeycode } from "@/hooks/use-keycode"
import { cn } from "@/lib/utils"

import { KeyButton } from "./key-button"

const useKeycodeMetadata = (keycode: number) => {
  const { getKeycodeMetadata } = useKeycode()

  return useMemo(
    () => getKeycodeMetadata(keycode),
    [getKeycodeMetadata, keycode],
  )
}

export function KeycodeButton({
  keycode,
  ...props
}: React.ComponentProps<typeof KeyButton> & { keycode: number }) {
  const keycodeMetadata = useKeycodeMetadata(keycode)

  return (
    <KeyButton {...props}>
      {(keycodeMetadata.display ?? [keycodeMetadata.name]).map((Variant, i) =>
        typeof Variant === "string" ? (
          <span key={i}>{Variant}</span>
        ) : (
          <Variant key={i} />
        ),
      )}
    </KeyButton>
  )
}

export function KeycodeButtonTooltip({
  keycode,
  children,
  className,
  ...props
}: { keycode: number } & React.ComponentProps<typeof TooltipTrigger>) {
  const keycodeMetadata = useKeycodeMetadata(keycode)

  if (!keycodeMetadata.tooltip) {
    return <>{children}</>
  }

  return (
    <Tooltip>
      <TooltipTrigger asChild className={cn("size-full", className)} {...props}>
        <div>{children}</div>
      </TooltipTrigger>
      <TooltipContent className="max-w-56 text-wrap">
        {keycodeMetadata.tooltip}
      </TooltipContent>
    </Tooltip>
  )
}
