// src/lib/configurator/settings/settings-tab.svelte
<!-- 
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
  import FixedScrollArea from "$lib/components/fixed-scroll-area.svelte"
  import { Button } from "$lib/components/ui/button"
  import * as Dialog from "$lib/components/ui/dialog"
  import { keyboardContext } from "$lib/keyboard"
  import { cn, type WithoutChildren } from "$lib/utils"
  import type { HTMLAttributes } from "svelte/elements"
  import { profileQueryContext } from "../queries/profile-query.svelte"

  const {
    class: className,
    ...props
  }: WithoutChildren<HTMLAttributes<HTMLDivElement>> = $props()

  const keyboard = keyboardContext.get()
  const { demo } = keyboard

  const profileQuery = profileQueryContext.get()
</script>

<div
  class={cn("mx-auto flex size-full max-w-3xl flex-col", className)}
  {...props}
>
  <FixedScrollArea class="flex flex-col gap-4 p-4">
    <div class="flex flex-col gap-2">
      <div class="grid text-sm">
        <span class="font-semibold">Restart Keyboard</span>
        <span class="text-pretty text-muted-foreground">
          The keyboard will disconnect and reconnect. No changes will be made to
          your keyboard settings.
        </span>
      </div>
      <div>
        <Button
          disabled={demo}
          onclick={() => keyboard.reboot()}
          size="sm"
          variant="outline"
        >
          Restart Keyboard
        </Button>
      </div>
    </div>
    <div class="flex flex-col gap-2">
      <div class="grid text-sm">
        <span class="font-semibold">Enter Bootloader Mode</span>
        <span class="text-pretty text-muted-foreground">
          The keyboard will restart and enter bootloader mode if it is supported
          by the firmware. No changes will be made to your keyboard settings.
        </span>
      </div>
      <div>
        <Button
          disabled={demo}
          onclick={() => keyboard.bootloader()}
          size="sm"
          variant="outline"
        >
          Enter Bootloader Mode
        </Button>
      </div>
    </div>
    <div class="flex flex-col gap-2">
      <div class="grid text-sm">
        <span class="font-semibold">Factory Reset</span>
        <span class="text-pretty text-muted-foreground">
          Revert the keyboard to its factory settings defined by the firmware.
          All user data and settings will be lost.
        </span>
      </div>
      <div>
        <Dialog.Root>
          <Dialog.Trigger>
            {#snippet child({ props })}
              <Button
                disabled={demo}
                size="sm"
                variant="destructive"
                {...props}
              >
                Factory Reset
              </Button>
            {/snippet}
          </Dialog.Trigger>
          <Dialog.Content>
            <Dialog.Header>
              <Dialog.Title>Factory Reset?</Dialog.Title>
              <Dialog.Description>
                Are you sure you want to factory reset your keyboard?
              </Dialog.Description>
            </Dialog.Header>
            <Dialog.Footer>
              <Dialog.Close>
                {#snippet child({ props })}
                  <Button size="sm" variant="outline" {...props}>Cancel</Button>
                {/snippet}
              </Dialog.Close>
              <Dialog.Close onclick={() => profileQuery.factoryReset()}>
                {#snippet child({ props })}
                  <Button size="sm" variant="destructive" {...props}>
                    Factory Reset
                  </Button>
                {/snippet}
              </Dialog.Close>
            </Dialog.Footer>
          </Dialog.Content>
        </Dialog.Root>
      </div>
    </div>
  </FixedScrollArea>
</div>

// src/components/configurator/settings/settings-tab.tsx
/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

"use client"

import { useBootloader } from "@/api/use-bootloader"
import { useFactoryReset } from "@/api/use-factory-reset"
import { useReboot } from "@/api/use-reboot"
import { useDevice } from "@/components/providers/device-provider"
import { Button, buttonVariants } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { ScrollArea } from "@/components/ui/scroll-area"

export function SettingsTab() {
  const { isDemo } = useDevice()

  const { mutate: reboot } = useReboot()
  const { mutate: bootloader } = useBootloader()
  const { mutate: factoryReset } = useFactoryReset()

  return (
    <ScrollArea className="flex-1">
      <div className="mx-auto flex w-full max-w-5xl flex-col gap-6 p-4">
        <div className="flex flex-col">
          <p className="font-semibold leading-none tracking-tight">
            Restart Device
          </p>
          <p className="mt-1 text-sm text-muted-foreground">
            Restart the device. No changes are made to the device configuration.
          </p>
          <div className="mt-3">
            <Button
              disabled={isDemo}
              variant="outline"
              onClick={() => reboot()}
            >
              Restart Device
            </Button>
          </div>
        </div>
        <div className="flex flex-col">
          <p className="font-semibold leading-none tracking-tight">
            Enter Bootloader
          </p>
          <p className="mt-1 text-sm text-muted-foreground">
            Restart the device and enter the bootloader. If the bootloader is
            not configured in the device firmware, nothing will happen.
          </p>
          <div className="mt-3">
            <Button
              disabled={isDemo}
              variant="outline"
              onClick={() => bootloader()}
            >
              Enter Bootloader
            </Button>
          </div>
        </div>
        <div className="flex flex-col">
          <p className="font-semibold leading-none tracking-tight">
            Factory Reset
          </p>
          <p className="mt-1 text-sm text-muted-foreground">
            Revert the device configuration to the default settings defined in
            the firmware.
          </p>
          <div className="mt-3">
            <Dialog>
              <DialogTrigger disabled={isDemo} asChild>
                <Button variant="destructive">Factory Reset</Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Factory Reset?</DialogTitle>
                  <DialogDescription>
                    Are you sure you want to reset the device to its default
                    settings? All changes will be lost and cannot be undone.
                  </DialogDescription>
                </DialogHeader>
                <DialogFooter>
                  <DialogClose
                    className={buttonVariants({
                      variant: "outline",
                      size: "sm",
                    })}
                  >
                    Cancel
                  </DialogClose>
                  <DialogClose
                    className={buttonVariants({
                      variant: "destructive",
                      size: "sm",
                    })}
                    onClick={() => factoryReset()}
                  >
                    Factory Reset
                  </DialogClose>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </div>
      </div>
    </ScrollArea>
  )
}
