// components/configurator/advanced-keys/config-menu/layout.tsx
/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { useConfiguratorAdvancedKeys } from "@/components/providers/configurator-provider"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"

import { useAdvancedKeysConfig } from "."
import { AdvancedKeysDeleteDialog } from "../common/delete-dialog"

export function AdvancedKeysConfigLayout({
  children,
  className,
  ...props
}: React.ComponentProps<"div">) {
  const { setIndex } = useConfiguratorAdvancedKeys()

  const {
    index,
    advancedKey,
    metadata: { title },
  } = useAdvancedKeysConfig()

  return (
    <div className={cn("flex size-full flex-col", className)} {...props}>
      <div className="flex items-center justify-between gap-4 p-4">
        <div className="font-semibold">{title}</div>
        <div className="flex items-center gap-2">
          <AdvancedKeysDeleteDialog
            asChild
            index={index}
            advancedKey={advancedKey}
          >
            <Button size="sm" variant="destructive">
              Delete
            </Button>
          </AdvancedKeysDeleteDialog>
          <Button onClick={() => setIndex(null)} size="sm">
            Done
          </Button>
        </div>
      </div>
      {children}
    </div>
  )
}

// src/lib/configurator/layout.svelte
<!-- 
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
  import GithubLink from "$lib/components/github-link.svelte"
  import ThemeSwitcher from "$lib/components/theme-switcher.svelte"
  import * as Sidebar from "$lib/components/ui/sidebar"
  import { Tabs } from "bits-ui"
  import type { ComponentProps } from "svelte"
  import { globalStateContext } from "./context.svelte"
  import ProfileSelect from "./profile-select.svelte"
  import ConfiguratorSidebar from "./sidebar/sidebar.svelte"

  const { children, ...props }: ComponentProps<typeof Sidebar.Provider> =
    $props()

  const globalState = globalStateContext.get()
</script>

<Tabs.Root bind:value={globalState.tab}>
  <Sidebar.Provider {...props}>
    <ConfiguratorSidebar />
    <Sidebar.Inset>
      <header class="flex h-14 shrink-0 items-center gap-4 px-4">
        <div class="flex flex-1 items-center gap-2">
          <Sidebar.Trigger class="-ml-1" />
          <Sidebar.Separator
            class="mr-2 data-[orientation=vertical]:h-4"
            orientation="vertical"
          />
          <ProfileSelect />
        </div>
        <div class="flex shrink-0 items-center gap-2">
          <GithubLink />
          <ThemeSwitcher />
        </div>
      </header>
      <main class="flex flex-1 flex-col">{@render children?.()}</main>
    </Sidebar.Inset>
  </Sidebar.Provider>
</Tabs.Root>
