// src/lib/configurator/remap/remap-keyboard.svelte
<!-- 
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
  import { KeyboardEditorKeyboard } from "$lib/components/keyboard-editor"
  import * as KeycodeButton from "$lib/components/keycode-button"
  import { Keycode } from "$lib/libhmk/keycodes"
  import { numberNullable, stringNullable } from "$lib/utils"
  import { ToggleGroup } from "bits-ui"
  import { remapStateContext } from "../context.svelte"
  import { remapQueryContext } from "../queries/remap-query.svelte"

  const remapState = remapStateContext.get()
  const { layer, key } = $derived(remapState)

  const remapQuery = remapQueryContext.get()
  const { current: keymap } = $derived(remapQuery.keymap)
</script>

<ToggleGroup.Root
  bind:value={
    () => stringNullable(key), (v) => (remapState.key = numberNullable(v))
  }
  type="single"
>
  {#snippet child({ props })}
    <KeyboardEditorKeyboard {...props}>
      {#snippet keyGenerator(key)}
        {#if !keymap}
          <KeycodeButton.Skeleton />
        {:else}
          <ToggleGroup.Item
            oncontextmenu={(e) => {
              e.preventDefault()
              remapQuery.set({ layer, offset: key, data: [Keycode.KC_NO] })
            }}
            value={String(key)}
          >
            {#snippet child({ props })}
              <KeycodeButton.Root
                keycode={keymap[layer][key]}
                showTooltip
                {...props}
              />
            {/snippet}
          </ToggleGroup.Item>
        {/if}
      {/snippet}
    </KeyboardEditorKeyboard>
  {/snippet}
</ToggleGroup.Root>

// components/configurator/remap/remap-keyboard.tsx
/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { ToggleGroup, ToggleGroupItem } from "@radix-ui/react-toggle-group"

import { KeyboardEditorKeyboard } from "@/components/common/keyboard-editor"
import { useConfigurator } from "@/components/providers/configurator-provider"
import { useKeyboard } from "@/components/providers/keyboard-provider"
import { useGetKeymap } from "@/queries/get-keymap"
import { useSetKeymap } from "@/queries/set-keymap"
import { Keycode } from "@/types/libhmk/keycodes"

import { KeyButtonSkeleton } from "../common/key-button"
import { KeycodeButton, KeycodeButtonTooltip } from "../common/keycode-button"

export function RemapKeyboard() {
  const {
    profile,
    remap: { layer, key, setKey },
  } = useConfigurator()
  const {
    metadata: { layout },
  } = useKeyboard()

  const { isSuccess, data: keymap } = useGetKeymap({ profile, layer })
  const { mutate: setKeymap } = useSetKeymap({ profile, layer })

  return (
    <ToggleGroup
      asChild
      onValueChange={(key) => setKey(key === "" ? null : parseInt(key))}
      type="single"
      value={key?.toString() ?? ""}
    >
      <KeyboardEditorKeyboard
        layout={layout}
        keyGenerator={(key) =>
          !isSuccess ? (
            <KeyButtonSkeleton />
          ) : (
            <KeycodeButtonTooltip keycode={keymap[key]}>
              <ToggleGroupItem asChild value={key.toString()}>
                <KeycodeButton
                  keycode={keymap[key]}
                  onContextMenu={(e) => {
                    e.preventDefault()
                    setKeymap({ offset: key, keymap: [Keycode.KC_NO] })
                    setKey(null)
                  }}
                />
              </ToggleGroupItem>
            </KeycodeButtonTooltip>
          )
        }
      />
    </ToggleGroup>
  )
}
