// src/components/configurator/common/switch.tsx
/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { Label } from "@/components/ui/label"
import { Switch as SwitchComponent } from "@/components/ui/switch"
import { cn } from "@/lib/utils"
import { HTMLAttributes } from "react"

interface SwitchProps extends HTMLAttributes<HTMLDivElement> {
  disabled?: boolean
  size?: "default" | "sm"
  id: string
  title: string
  description?: string
  checked?: boolean
  onCheckedChange?: (checked: boolean) => void
}

export function Switch({
  disabled,
  size,
  id,
  title,
  description,
  checked,
  onCheckedChange,
  className,
}: SwitchProps) {
  return (
    <div
      className={cn(
        "flex w-full flex-col",
        disabled && "pointer-events-none opacity-50",
        className,
      )}
    >
      <div className="flex items-center gap-2">
        <SwitchComponent
          id={id}
          checked={checked}
          onCheckedChange={onCheckedChange}
        />
        <Label
          htmlFor={id}
          className={cn(
            "font-semibold tracking-tight",
            size === "sm" ? "text-sm" : "text-base",
          )}
        >
          {title}
        </Label>
      </div>
      {description && (
        <p className="mt-1 text-sm text-muted-foreground">{description}</p>
      )}
    </div>
  )
}

// src/lib/components/switch.svelte
<!-- 
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
-->

<script lang="ts">
  import { InfoIcon } from "@lucide/svelte"
  import { cn, type WithoutChildren } from "$lib/utils"
  import type { HTMLAttributes } from "svelte/elements"
  import { Label } from "./ui/label"
  import { Switch } from "./ui/switch"
  import * as Tooltip from "./ui/tooltip"

  let {
    class: className,
    disabled,
    id,
    title,
    tooltip,
    description,
    checked = $bindable(false),
    ref = $bindable(null),
    onCheckedChange,
    ...props
  }: WithoutChildren<HTMLAttributes<HTMLDivElement>> & {
    disabled?: boolean
    id: string
    title: string
    tooltip?: string
    description?: string
    checked?: boolean
    ref?: HTMLElement | null
    onCheckedChange?: (checked: boolean) => void
  } = $props()
</script>

<div class={cn("grid gap-1", className)} {...props}>
  <div class="flex items-center gap-2">
    <Switch bind:checked bind:ref {disabled} {id} {onCheckedChange} />
    <Label for={id}>{title}</Label>
    {#if tooltip}
      <Tooltip.Root>
        <Tooltip.Trigger>
          <InfoIcon class="size-4" />
          <span class="sr-only">Info</span>
        </Tooltip.Trigger>
        <Tooltip.Content class="max-w-56 text-pretty">
          {tooltip}
        </Tooltip.Content>
      </Tooltip.Root>
    {/if}
  </div>
  {#if description}
    <span
      class={cn(
        "text-sm text-pretty text-muted-foreground",
        disabled && "opacity-50",
      )}
    >
      {description}
    </span>
  {/if}
</div>
